version: '3'

# Taskfile.dev


vars:
  DL_FOLDER: '/mnt/volute/SteamLibrary/steamapps/common/Deadlock'


tasks:

  get_all_vars:
    cmds:
    - "echo 'Run in game: cvarlist'"
    - "con_logfile $(pwd)/filename.txt; cvarlist; con_logfile ''"

  get_vars_modifiers:
    - modifier_dump_list

  create_tree:
    cmds:
      - tree -a --prune -p -h -D -o deadlock_file_tree.txt {{.DL_FOLDER}}

  sync_configs:
    cmds:
      - rsync --archive {{.DL_FOLDER}}/game/citadel/cfg/* ./game